// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9pEduke9C6f-pcjHXLYyAAUNjHPnz2n8',
    appId: '1:90108471288:web:3ed0f82aa2cf183830580d',
    messagingSenderId: '90108471288',
    projectId: 'advanceexam-6951d',
    authDomain: 'advanceexam-6951d.firebaseapp.com',
    storageBucket: 'advanceexam-6951d.firebasestorage.app',
    measurementId: 'G-QTWLQ7RB9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs5plTT6rDwautTAT4j2oyP1Z907oAg8E',
    appId: '1:90108471288:android:0c1261914001bb4130580d',
    messagingSenderId: '90108471288',
    projectId: 'advanceexam-6951d',
    storageBucket: 'advanceexam-6951d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH7-NTJ0Y1M4AJVhs8zHloqpcNy2WjGP8',
    appId: '1:90108471288:ios:228ae4559944780030580d',
    messagingSenderId: '90108471288',
    projectId: 'advanceexam-6951d',
    storageBucket: 'advanceexam-6951d.firebasestorage.app',
    iosBundleId: 'com.example.advanceExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH7-NTJ0Y1M4AJVhs8zHloqpcNy2WjGP8',
    appId: '1:90108471288:ios:228ae4559944780030580d',
    messagingSenderId: '90108471288',
    projectId: 'advanceexam-6951d',
    storageBucket: 'advanceexam-6951d.firebasestorage.app',
    iosBundleId: 'com.example.advanceExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9pEduke9C6f-pcjHXLYyAAUNjHPnz2n8',
    appId: '1:90108471288:web:c25aa2bd0fa0aba330580d',
    messagingSenderId: '90108471288',
    projectId: 'advanceexam-6951d',
    authDomain: 'advanceexam-6951d.firebaseapp.com',
    storageBucket: 'advanceexam-6951d.firebasestorage.app',
    measurementId: 'G-BT5STLP4RD',
  );
}
